"""Upgrade User Model

Revision ID: 767bc22d6b9f
Revises: e6b7e4165645
Create Date: 2023-05-20 18:37:52.754040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767bc22d6b9f'
down_revision = 'e6b7e4165645'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
